version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "IMAGE_REPO_NAME: $IMAGE_REPO_NAME"
      - echo "CODEBUILD_BUILD_NUMBER: $CODEBUILD_BUILD_NUMBER"
      - echo "AWS_ACCOUNT_ID: $AWS_ACCOUNT_ID"
      - echo "AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION"
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t "$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER" .
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$CODEBUILD_BUILD_NUMBER"

environment:
  variables:
    IMAGE_REPO_NAME: "your-repo-name"
    AWS_ACCOUNT_ID: "your-aws-account-id"
    AWS_DEFAULT_REGION: "your-aws-region"
    CODEBUILD_BUILD_NUMBER: "$CODEBUILD_BUILD_NUMBER"
