apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-configmap
data:
  DB_NAME: "postgres"
  DB_USER: "postgres"
  DB_HOST: "my-postgres-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-postgresql
type: Opaque
data:
  DB_PASSWORD: Gv1cUjlBOM