apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-db-configmap
data:
  DB_NAME: "postgres"
  DB_USERNAME: "postgres"
  DB_HOST: "my-postgres-postgresql.default.svc.cluster.local"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-db-password
type: Opaque
data:
  DB_PASSWORD: R3YxY1VqbEJPTQ==
